matrix:
  include:
    - language: python
      python: 3.7
      install:
        - pip3 install -r requirements.txt
      script:
        - echo "done"
    - language: node_js
      node_js: 10.16.3
      script:
        - npm run eslint