# Generated by Django 2.2.9 on 2020-02-14 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='alumni',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_time'),
        ),
        migrations.AddField(
            model_name='job',
            name='alumni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Alumni'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='dob',
            field=models.DateField(max_length=100, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer_org',
            field=models.CharField(max_length=30, verbose_name='employer_org'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=20, verbose_name='job_title'),
        ),
        migrations.CreateModel(
            name='Unemployed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(max_length=100, verbose_name='start_date')),
                ('end_date', models.DateField(max_length=100, null=True, verbose_name='end_date')),
                ('desired_job', models.CharField(max_length=20, verbose_name='desired_job')),
                ('alumni', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Alumni')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(max_length=100, verbose_name='start_date')),
                ('end_date', models.DateField(max_length=100, null=True, verbose_name='end_date')),
                ('name_of_institution', models.CharField(max_length=30, verbose_name='name_of_institution')),
                ('type_of_institution', models.CharField(max_length=30, verbose_name='type_of_institution')),
                ('program', models.CharField(max_length=20, verbose_name='prog')),
                ('alumni', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Alumni')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
