# Generated by Django 3.0.3 on 2020-07-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnus',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('masters', 'Masters Degree'), ('associate', 'Associate Degree'), ('bachelors', "Bachelor's Degree"), ('training program', 'Training Program'), ('high school degree', 'High School Diploma'), ('middle school degree', 'Middle School Diploma'), ('phd', 'Ph. D'), ('minor', 'Minor')], default='training program', max_length=30),
        ),
    ]
