# Generated by Django 2.2.9 on 2020-02-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='date_of_birth'),
        ),
    ]
