# Generated by Django 3.0.3 on 2020-07-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200715_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree"), ('Associate Degree', 'Associate Degree'), ('Training Program', 'Training Program'), ('Minor', 'Minor'), ('Ph. D', 'Ph. D'), ('High School Diploma', 'High School Diploma'), ('Middle School Diploma', 'Middle School Diploma'), ('Masters Degree', 'Masters Degree')], default='Training Program', max_length=30),
        ),
    ]
