# Generated by Django 2.2.9 on 2020-02-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200214_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='type_of_degree',
            field=models.CharField(choices=[('mids', 'Middle School Diploma'), ('highs', 'Sophomore'), ('train', 'Training Program'), ('assoc', 'Associate Degree'), ('bach', 'Bachelors Degree'), ('ms', 'Masters Degree'), ('phd', 'Ph. D')], default='Training Program', max_length=20, verbose_name='degree_level'),
        ),
        migrations.AddField(
            model_name='unemployed',
            name='degree_level',
            field=models.CharField(choices=[('mids', 'Middle School Diploma'), ('highs', 'Sophomore'), ('train', 'Training Program'), ('assoc', 'Associate Degree'), ('bach', 'Bachelors Degree'), ('ms', 'Masters Degree'), ('phd', 'Ph. D')], default='Training Program', max_length=20, verbose_name='degree_level'),
        ),
    ]
