# Generated by Django 3.0.7 on 2020-07-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200718_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('high school degree', 'High School Diploma'), ('training program', 'Training Program'), ('bachelors', "Bachelor's Degree"), ('minor', 'Minor'), ('masters', 'Masters Degree'), ('phd', 'Ph. D'), ('associate', 'Associate Degree'), ('middle school degree', 'Middle School Diploma')], default='training program', max_length=30),
        ),
    ]
