# Generated by Django 2.2.10 on 2020-02-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200228_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_time',
            field=models.DateTimeField(verbose_name='updated_time'),
        ),
    ]
