# Generated by Django 2.2.10 on 2020-03-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_time'),
        ),
    ]
