# Generated by Django 2.2.5 on 2020-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='jobs',
            field=models.ManyToManyField(to='api.Job'),
        ),
    ]
